// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIq2YUxhopAqscuD_-pzYV-ABNHIy-PYI',
    appId: '1:693686315099:web:e686efc4e895919f2df77e',
    messagingSenderId: '693686315099',
    projectId: 'ecommerce-app-d429d',
    authDomain: 'ecommerce-app-d429d.firebaseapp.com',
    storageBucket: 'ecommerce-app-d429d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8u42Y3NvUcQfKPdu6Ic_HmNGNibHTduA',
    appId: '1:693686315099:android:59fbd134217f485f2df77e',
    messagingSenderId: '693686315099',
    projectId: 'ecommerce-app-d429d',
    storageBucket: 'ecommerce-app-d429d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUD0KjtKTd9zctY6yfVB711FaZNx0eQfY',
    appId: '1:693686315099:ios:36e763a14e0c7e1e2df77e',
    messagingSenderId: '693686315099',
    projectId: 'ecommerce-app-d429d',
    storageBucket: 'ecommerce-app-d429d.appspot.com',
    iosBundleId: 'com.example.ecommerceFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUD0KjtKTd9zctY6yfVB711FaZNx0eQfY',
    appId: '1:693686315099:ios:36e763a14e0c7e1e2df77e',
    messagingSenderId: '693686315099',
    projectId: 'ecommerce-app-d429d',
    storageBucket: 'ecommerce-app-d429d.appspot.com',
    iosBundleId: 'com.example.ecommerceFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIq2YUxhopAqscuD_-pzYV-ABNHIy-PYI',
    appId: '1:693686315099:web:54c28d14cddceae42df77e',
    messagingSenderId: '693686315099',
    projectId: 'ecommerce-app-d429d',
    authDomain: 'ecommerce-app-d429d.firebaseapp.com',
    storageBucket: 'ecommerce-app-d429d.appspot.com',
  );
}
